FROM openjdk:8
EXPOSE 8761
ADD target/eureka-discovery-service-0.0.1-SNAPSHOT.jar eureka-discovery-service-0.0.1-SNAPSHOT.jar 
ENTRYPOINT ["java","-jar","/eureka-discovery-service-0.0.1-SNAPSHOT.jar"]