FROM openjdk:8
EXPOSE 8081
ADD target/processPensionMicroservice-0.0.1-SNAPSHOT.jar processPensionMicroservice-0.0.1-SNAPSHOT.jar 
ENTRYPOINT ["java","-jar","/processPensionMicroservice-0.0.1-SNAPSHOT.jar"]