FROM openjdk:8
EXPOSE 8083
ADD target/pensionerDisbursementMicroservice-0.0.1-SNAPSHOT.jar pensionerDisbursementMicroservice-0.0.1-SNAPSHOT.jar 
ENTRYPOINT ["java","-jar","/pensionerDisbursementMicroservice-0.0.1-SNAPSHOT.jar"]