FROM openjdk:8
EXPOSE 8085
ADD target/pensionManagementSystem-0.0.1-SNAPSHOT.jar pensionManagementSystem-0.0.1-SNAPSHOT.jar 
ENTRYPOINT ["java","-jar","/pensionManagementSystem-0.0.1-SNAPSHOT.jar"]