FROM openjdk:8
EXPOSE 8082
ADD target/pensionerDetailsMicroservice-0.0.1-SNAPSHOT.jar pensionerDetailsMicroservice-0.0.1-SNAPSHOT.jar 
ENTRYPOINT ["java","-jar","/pensionerDetailsMicroservice-0.0.1-SNAPSHOT.jar"]